[phases.setup]
nixPkgs = [
  "php",
  "php81Extensions.pdo_mysql",  # toto je klíčové!
  "php81Extensions.mbstring",
  "php81Extensions.openssl",
  "php81Packages.composer"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:clear",
  "php artisan route:clear",
  "php artisan view:clear"
]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/"